name: Maydev
name-eng: Jiun, Bae
description: Do not lose the humility of new learning
title: blog.Maydev
ori_url: 'https://MaybeS.github.io'
url: 'blog.maydev.org'
author: 'Maydev'
permalink: /posts/:title/
type: 'blog'

resume: 'https://drive.google.com/file/d/0BwQhFb-IfuTFcW03ZFlicTRuWVE/view?usp=sharing'
resume_update: '2017-12-30'
avatar: 'https://avatars0.githubusercontent.com/u/7712538?v=3&s=460'
attach: 'https://raw.githubusercontent.com/MaybeS/MaybeS.github.io/master/assets/images/attach/'
github: 'https://github.com/MaybeS'

paginate: 50
baseurl: ""
domain_name: 'https://blog.maydev.org'
google_analytics: 'UA-72426393-2'
disqus_shortname: 'maydev'

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-paginate
    - jekyll-sitemap
  
future: true
fbcomments: true

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
