name: Maydev
description: Maydev personal blog
title: blog.Maydev
ori_url: 'https://MaybeS.github.io'
url: 'blog.maydev.org'
author: 'Maydev'
permalink: /:year/:title/
type: 'blog'

resume: 'https://github.com/MaybeS/MaybeS.github.io/blob/master/assets/data/resume.pdf?raw=true'
avatar: 'https://avatars0.githubusercontent.com/u/7712538?v=3&s=460'
attach: 'https://raw.githubusercontent.com/MaybeS/MaybeS.github.io/master/assets/images/attach/'
github: 'https://github.com/MaybeS'

paginate: 50
base: /
domain_name: 'https://blog.maydev.org'
google_analytics: 'UA-72426393-2'
disqus_shortname: 'maydev'

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
future: true

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post