name: Maydev
description: personal brand website
url-link: maydev.org
paginate: 10

author:
  name: Ji Un, Bae
  nick: maybe
  email: maytryark@gmail.com
  twitter: maytryark
  facebook: maytryark
  github: maybes
