name: Jiun
name-eng: Jiun, Bae
description: 그럴듯한 헛소리를 합니다.
title: blog.jiun.dev
ori_url: 'https://jiunbae.github.io'
url: 'https://blog.jiun.dev'
author: 'Jiun'
permalink: /posts/:title/
type: 'blog'

resume: 'https://drive.google.com/file/d/1Ce3XE-yL79yxczm6KWcGFHTbOH0OxTW0/view?usp=sharing'
resume_update: '2021-03-29'
avatar: 'https://avatars0.githubusercontent.com/u/7712538?v=3&s=460'
attach: 'https://raw.githubusercontent.com/jiunbae/jiunbae.github.io/master/assets/images/attach/'
github: 'https://github.com/jiunbae'

paginate: 50
baseurl: ""
domain_name: 'https://blog.jiun.dev'
google_analytics: 'UA-72426393-2'
disqus_shortname: 'maydev'

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-paginate
    - jekyll-sitemap
  
future: true
comments: true

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
