name: Maydev
description: Maydev Studio

markdown: kramdown
highlighter: rouge

paginate: 50
baseurl: /
domain_name: 'https://MaybeS.github.io'
google_analytics: ''
disqus_shortname: 'maydev'

resume: 'https://goo.gl/tZ5mKv'
avatar: 'https://avatars0.githubusercontent.com/u/7712538?v=3&s=460'
attach: 'https://raw.githubusercontent.com/MaybeS/MaybeS.github.io/master/assets/images/attach/'
github: 'https://github.com/MaybeS'

url:            'https://MaybeS.github.io'
author:         'Maydev'
permalink:       /:year/:title/
gems: [jekyll-paginate]
future: true

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post